name: LLM Based Autograder
description: Autograder for GitHub Classroom assignments using LLM
author: Nikita Galkin

branding:
  icon: check-circle
  color: blue

inputs:
  prompt_file_path:
    description: Path to for the assignment
    required: true
  gemini_api_key:
    description: Gemini API key
    required: true

outputs:
  result:
    description: 'Runner output'

runs:
  using: node20
  main: dist/index.js
